# Terraform Provider testing workflow.
name: Tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "CHANGELOG.md"
  push:
    branches:
      - master
      - "feature/**"
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "CHANGELOG.md"

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod download
      - run: go build -o terraform-provider-voipms -v .
      - run: go test -v -cover -timeout=120s ./internal/...
